version: '3'
services:
    postgres:
        image: postgres:13-alpine
        environment:
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
        ports:
            - "5432:5432"
        volumes:
            - ./ca:/var/lib/postgresql/
